### ISSUE TITLE
briekit-event error:  UnboundLocalError: local variable 'exons' referenced before assignment

### ISSUE THREAD

**Issue by jihongma1010** [huangyh09/briekit#2]
hi, I got this error when I run
briekit-event -a /disk1/reference_genome/hg38_ucsc_ercc/Gencodev32_hg38_ercc_refseq.gtf -o /disk2/brie_rnasplicing_bc25/bc25_as/
Making GFF alternative events annotation...
Input annotation files: /disk1/reference_genome/hg38_ucsc_ercc/Gencodev32_hg38_ercc_refseq.gtf
Output dir: /disk2/brie_rnasplicing_bc25/bc25_as/
('Reading table', '/disk1/reference_genome/hg38_ucsc_ercc/Gencodev32_hg38_ercc_refseq.gtf')
Traceback (most recent call last):
File "/home/JHma/miniconda3/envs/RNASEQ/bin/briekit-event", line 11, in 
load_entry_point('briekit==0.2.2', 'console_scripts', 'briekit-event')()
File "build/bdist.linux-x86_64/egg/briekit/events/event_maker.py", line 175, in main
File "build/bdist.linux-x86_64/egg/briekit/events/event_maker.py", line 69, in defineAllSplicing
File "build/bdist.linux-x86_64/egg/briekit/events/event_maker.py", line 39, in prepareSplicegraph
File "build/bdist.linux-x86_64/egg/briekit/events/parseTables.py", line 85, in populateSplicegraph
File "build/bdist.linux-x86_64/egg/briekit/events/parseTables.py", line 64, in readTable_gff
UnboundLocalError: local variable 'exons' referenced before assignment
Could you help me? Thanks

**Comment by huangyh09** [comment]
Hi,

I'm not very sure what causes this issue. There are two possibilities:
1) the format of `Gencodev32_hg38_ercc_refseq.gtf` is not compartible. The required format is here: http://diceseq.sourceforge.net/manual.html#annotation-format
2) not sure if you are using Python 2.7, as Python 3 is not compatible.

Let me know if it is any of them.
Yuanhua
